apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloud-ide
  labels:
    app: backend
    app.kubernetes.io/name: cloud-ide
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: backend
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      protocol: TCP
