apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-ide

resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - network-policy.yaml
  - ingress.yaml
  - pdb.yaml
  - observability/prometheus-configmap.yaml
  - observability/prometheus-deployment.yaml
  - observability/prometheus-service.yaml
  - observability/grafana-datasources-configmap.yaml
  - observability/grafana-dashboards-configmap.yaml
  - observability/grafana-deployment.yaml
  - observability/grafana-service.yaml
  - observability/loki-configmap.yaml
  - observability/loki-deployment.yaml
  - observability/loki-service.yaml
  - observability/promtail.yaml
