apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cloud-ide
  labels:
    app: mysql
    app.kubernetes.io/name: cloud-ide
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
