apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: cloud-ide
  labels:
    app: loki
    app.kubernetes.io/name: cloud-ide
    app.kubernetes.io/component: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      name: http
