apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cloud-ide
  labels:
    app: prometheus
    app.kubernetes.io/name: cloud-ide
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      name: http
